# Site settings
title: CDAT
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cdat.llnl.gov" # the base hostname & protocol for your site
logo: "https://raw.githubusercontent.com/PCMDI/pcmdi_metrics/master/share/pcmdi/CDATLogo_140x49px_72dpi.png"
# Build settings
markdown: kramdown
collections:
  examples:
    output: true
highlighter: pygments