context:
  data:
    home_url: index.html
    nav_hover: yes
    menu:
      - title: UV<img src="media/images/uvcdat.png" style=margin-top:-7px />CDAT
        url: index.html
      - title: About
        url:
          - title: Mission
            url: mission.html
          - title: Governance
            url: governance.html
          - title: Committee
            url: committee.html
          - title: Acknowledgments
            url: acknowledgments.html
      - title: Press 
        url:
          - title: ACME Demos
            url: demos.html
          - title: Publications
            url: publications.html
          - title: Reports
            url: reports.html
          - title: Presentations
            url: presentations.html
          - title: Design Documents
            url: design.html
          - title: Animations
            url: animations.html
          - title: Use Cases
            url: https://github.com/UV-CDAT/uvcdat/wiki/Use-Cases
          - title: Releases
            url: https://github.com/UV-CDAT/uvcdat/wiki/Roadmap-to-Release
      - title: Installing
        url: installing.html
      - title: Gallery
        url: gallery.php
      - title: Contribute
        url: https://github.com/UV-CDAT/uvcdat/wiki
      - title: User Guides
        url:
          - title: CDAT
            url: http://uv-cdat.github.io/cdat-site/
          - title: Manuals
            url: http://uv-cdat.github.io/cdat-site/manuals.html
          - title: Tutorials
            url: tutorials.html
          - title: Mailing list
            url: mailing-list.html
          - title: Wiki
            url: https://github.com/UV-CDAT/uvcdat/wiki
site_title: UV-CDAT
media_url: media
mode: development
plugins: [hyde.ext.plugins.meta.MetaPlugin, hyde.ext.plugins.auto_extend.AutoExtendPlugin,
  hyde.ext.plugins.syntext.SyntextPlugin, hyde.ext.plugins.textlinks.TextlinksPlugin]
