context:
  data:
    home_url: index.html
    nav_hover: yes
    menu:
      - title: UV<img src="media/images/uvcdat.png" style=margin-top:-7px />CDAT
        url: index.html
      - title: About
        url:
          - title: Mission
            url: mission.html
          - title: Governance
            url: governance.html
          - title: Committee
            url: committee.html
          - title: Acknowledgments
            url: acknowledgments.html
      - title: Documents
        url:
          - title: Publications
            url: publications.html
          - title: Reports
            url: reports.html
          - title: Presentations
            url: presentations.html
          - title: Design Documents
            url: design.html
          - title: Animations
            url: animations.html
          - title: Use Cases
            url: https://github.com/UV-CDAT/uvcdat/wiki/Use-Cases
      - title: Installing
        url: installing.html
      - title: Contribute
        url: https://github.com/UV-CDAT/uvcdat/wiki
      - title: Help
        url:
          - title: Tutorials
            url: tutorials.html
          - title: Support Forum
            url: http://askbot-uvcdat.llnl.gov
          - title: Mailing list
            url: mailing-list.html
          - title: Wiki
            url: https://github.com/UV-CDAT/uvcdat/wiki
    site_title: UV-CDAT
    carousel:
      - caption: Sample output
        image: media/images/gallery/CelinesCaliforniaPlot.png
      - caption: Sample output
        image: media/images/gallery/figure3b.png
      - caption: Sample output
        image: media/images/gallery/Figure5a.png
      - caption: Sample output
        image: media/images/gallery/Figure5b.png
      - caption: Sample output
        image: media/images/gallery/Figure5c.png
      - caption: Sample output
        image: media/images/gallery/Figure5d.png
      - caption: Sample output
        image: media/images/gallery/GlyphVolume-1.jpg
      - caption: Sample output
        image: media/images/gallery/grid.png
      - caption: Sample output
        image: media/images/gallery/GUI_and_PipelineA.png
      - caption: Sample output
        image: media/images/gallery/GUI_and_PipelineB.png
      - caption: Sample output
        image: media/images/gallery/GUI_and_PipelineC.png
      - caption: Sample output
        image: media/images/gallery/GUI_and_PipelineD.png
      - caption: Sample output
        image: media/images/gallery/HR-RH-VR-Slicer-2.jpg
      - caption: Sample output
        image: media/images/gallery/Image-2-CompositeA.png
      - caption: Sample output
        image: media/images/gallery/Image-2-CompositeB.png
      - caption: Sample output
        image: media/images/gallery/Image-2-CompositeC.png
      - caption: Sample output
        image: media/images/gallery/Image-2-CompositeD.png
      - caption: Sample output
        image: media/images/gallery/Image-2-CompositeE.png
      - caption: Sample output
        image: media/images/gallery/Image-2-CompositeF.png
      - caption: UV-CDAT Power Wall
        image: media/images/gallery/UVCDAT-Hyperwall.jpg
media_url: media
mode: development
plugins: [hyde.ext.plugins.meta.MetaPlugin, hyde.ext.plugins.auto_extend.AutoExtendPlugin,
  hyde.ext.plugins.syntext.SyntextPlugin, hyde.ext.plugins.textlinks.TextlinksPlugin]
