context:
  data:
    home_url: index.html
    menu:
    - title: uv-cdat.org
      url: index.html
    - title: About
      url:
      - title: Mission
        url: mission.html
      - title: Publications
        url: publications.html
      - title: Presentations
        url: presentations.html
      - title: Governance
        url: governance.html
      - title: Acknowledgments
        url: acknowledgments.html
    - title: Download
      url: download.html
    - title: Contribute
      url:
      - title: Mailing list
        url: mailing-list.html
      - title: Developers
        url: developers.html
    - title: Progress
      url: progress.html
    site_title: UV-CDAT.org
media_url: media
mode: development
plugins: [hyde.ext.plugins.meta.MetaPlugin, hyde.ext.plugins.auto_extend.AutoExtendPlugin,
  hyde.ext.plugins.syntext.SyntextPlugin, hyde.ext.plugins.textlinks.TextlinksPlugin]
