context:
  data:
    home_url: index.html
    nav_hover: yes
    brand:
     title: UV<img src="/media/images/uvcdat.png" style="margin-top:-7px" />CDAT
     url: /index.html
    menu:
        - title: Gallery
          url: /gallery.php
        - title: Installing
          url: /installing.html
        - title: Documentation
          url:
            - title: CDMS
              url: /documentation/cdms/cdms.html
            - title: CDAT Utilities
              url: /documentation/utilities/utilities.html
            - title: VCS
              url: /documentation/vcs/vcs.html
            - title: Tutorials
              url: /tutorials.html
            - title: Wiki
              url: https://github.com/UV-CDAT/uvcdat/wiki
        - title: Contribute
          url: https://github.com/UV-CDAT/uvcdat/wiki
        - title: Contact
          url: /contact.html
site_title: UV-CDAT
media_url: /media
mode: development
plugins:
  - hyde.ext.plugins.meta.MetaPlugin
  - hyde.ext.plugins.auto_extend.AutoExtendPlugin
  - hyde.ext.plugins.syntext.SyntextPlugin
  - hyde.ext.plugins.textlinks.TextlinksPlugin
jinja2:
  filters:
    gfm: plugins.gfm.gfm
    dump: plugins.dump.dump
gfm:
  table_class: table
  space_headers: false
  code_fence: true
