context:
  data:
    home_url: index.html
    menu:
      - title: UVC-DAT.org
        url: index.html
      - title: About
        url:
          - title: Mission
            url: mission.html
          - title: Governance
            url: governance.html
          - title: Committee
            url: committee.html
          - title: Acknowledgments
            url: acknowledgments.html
      - title: Documents
        url:
          - title: Publications
            url: publications.html
          - title: Conferences
            url: conferences.html
          - title: Presentations
            url: presentations.html
      - title: Build
        url:
          - title: Releases
            url: releases.html
          - title: Installation
            url: installation.html
      - title: Download
        url: "http://sourceforge.net/projects/cdat/files/Releases/UV-CDAT/1.3"
      - title: Contribute
        url:
          - title: Tutorials
            url: tutorial.html
          - title: Developer info
            url: developers.html
          - title: GitHub
            url: "https://github.com/uv-cdat"
          - title: Issues
            url: "https://github.com/UV-CDAT/uvcdat/issues"
          - title: Help
            url: http://askbot.uv-cdat.org/
          - title: Contact
            url: contact.html
          - title: Mailing list
            url: mailing-list.html
    site_title: UV-CDAT.org
media_url: media
mode: development
plugins: [hyde.ext.plugins.meta.MetaPlugin, hyde.ext.plugins.auto_extend.AutoExtendPlugin,
  hyde.ext.plugins.syntext.SyntextPlugin, hyde.ext.plugins.textlinks.TextlinksPlugin]
