mode: development # Change to "production" before generating a production deployment
media_root: media # Relative path from content folder.
media_url: media # URL where the media files are served from.
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
context:
    data:
        site_title: Site Name
        author:
            name: Your Name Here
            url: "http://example.com"
        google_analytics_id: UA-XXXXX-YY
        home_url: index.html
        menu:
            - title: Home
              url: index.html
            - title: Landing
              url: landing.html
